spring:
  datasource:
    url: jdbc:h2:mem:mybatis-test
    username: sa
    password:
    schema: classpath:h2/schema.sql

  h2:
    console:
      enabled: true
      path: /h2-console

mybatis:
  mapper-locations: mapper/**/*.xml
  mybatis.type-aliases-package: com.example.demo.mapper, com.example.demo.model 
