DROP TABLE IF EXISTS MEMBER;

DROP TABLE IF EXISTS BOARD;

CREATE TABLE MEMBER(MEMBERID INT NOT NULL AUTO_INCREMENT, NAME VARCHAR2(255) NOT NULL, PRIMARY KEY(MEMBERID));

CREATE TABLE BOARD(BOARDID INT NOT NULL AUTO_INCREMENT, TITLE VARCHAR2(255) NOT NULL, CONTENT VARCHAR2(255) NOT NULL, PRIMARY KEY(BOARDID));